[tool.poetry]
name = "aws-lambda-ecs-riemann-reload"
version = "0.1.0"
description = "An AWS Lambda that will re-deploy the Riemann consumer or producer services running in ECS, when triggered by an SNS notification"
authors = ["Vítor Brandão <109226+vitorbrandao@users.noreply.github.com>"]
maintainers = ["Team Telemetry"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.17.85"

[tool.poetry.dev-dependencies]
aws-lambda-context = "^1.1.0"
aws-lambda-powertools = "^1.16.1"
bandit = "^1.7.0"
black = "^21.5b2"
moto = "^2.0.8"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
safety = "^1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
