Transform: AWS::Serverless-2016-10-31

Resources:
  EcsRiemannReload:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../../src
      FunctionName: ecs-riemann-reload
      Handler: handler.lambda_handler
      Role: EcsRiemannReloadRole
      Runtime: python3.8
